name: Build and Deploy Website

on:
  push:
    branches:
      - main  # Make sure this matches your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Start Timer
        run: echo "Start time: $(date)"

      - name: Deploy Website
        run: |
          echo "Building and deploying your site..."
          # Add any specific build commands here if needed
          # For example, if using a static site generator, add its build commands
          echo "Site deployed!"

      - name: End Timer
        run: echo "End time: $(date)"
